<a href="https://colab.research.google.com/github/ishwerdutt/pytorch/blob/main/Autograd.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
print(torch.__version__)

2.5.1+cu124


In [ ]:
if torch.cuda.is_available():
    print("CUDA is available")
else:
    print("CUDA is not available")

CUDA is not available


In [ ]:
x = torch.tensor(3.0, requires_grad=True)


In [ ]:
y = x*x

In [ ]:
y

tensor(9., grad_fn=<MulBackward0>)

In [ ]:

import math
def dy_dx(x):
  dy_dx = 2*x
  return dy_dx

In [ ]:
dy_dx(x)

tensor(6., grad_fn=<MulBackward0>)

In [ ]:
y.backward()

In [ ]:
x.grad

tensor(6.)

Steps during training
1. Forward pass:- calculation of output *w.x + b*
2. backward pass:- calulation of error
loss function let's say f(x);
 f(x) = y_pred - y
 df/dw = d/dw * (y_pred - y)

3. In the above step we need to calculate the derivatives.
And then we need to update weight and biases based on the gradient descent algorithm.
4. w_new = w_old - dl/dw
where L is the loss function based upon the task/algorithm used





# Examples

In [1]:
import torch as t
print(t.__version__)

2.5.1+cu124


In [16]:
## define some random function
t.manual_seed(42)
a =t.rand((2, 3), requires_grad=True)
b = t.rand((2, 3), requires_grad=True)

In [7]:
a, b

(tensor([[0.8823, 0.9150, 0.3829],
         [0.9593, 0.3904, 0.6009]]),
 tensor([[0.2566, 0.7936, 0.9408],
         [0.1332, 0.9346, 0.5936]]))

In [21]:
f_x = 3*a**3 - 5*b**2

In [22]:
f_x

tensor([[ 1.7311, -0.8511, -4.2569],
        [ 2.5598, -4.1888, -1.1108]], grad_fn=<SubBackward0>)

## derivative with respect to a


In [23]:
d_f_d_a = 9*a**2

In [24]:
d_f_d_a

tensor([[7.0056, 7.5351, 1.3193],
        [8.2824, 1.3720, 3.2497]], grad_fn=<MulBackward0>)

## derivative with respect to b

In [25]:
df_db = -10*b

In [26]:
df_db

tensor([[-2.5657, -7.9364, -9.4077],
        [-1.3319, -9.3460, -5.9358]], grad_fn=<MulBackward0>)

In [27]:
external_grad = t.tensor([[1., 1., 1.], [1., 1., 1.]], requires_grad=True)
f_x.backward(external_grad)

In [30]:
a.grad

tensor([[7.0056, 7.5351, 1.3193],
        [8.2824, 1.3720, 3.2497]])

In [31]:
b.grad

tensor([[-2.5657, -7.9364, -9.4077],
        [-1.3319, -9.3460, -5.9358]])