<a href="https://colab.research.google.com/github/ishwerdutt/pytorch/blob/main/Pytorch_work_flow_or_training_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as t

In [2]:
print(t.__version__)

2.5.1+cu124


In [3]:
if t.cuda.is_available():
  print("cuda-gpu is available")
else:
  print("not available")

cuda-gpu is available


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [6]:
df.head()

id diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst  Unnamed: 32
0    842302         M        17.99  ...          0.4601                  0.11890          NaN
1    842517         M        20.57  ...          0.2750                  0.08902          NaN
2  84300903         M        19.69  ...          0.3613                  0.08758          NaN
3  84348301         M        11.42  ...          0.6638                  0.17300          NaN
4  84358402         M        20.29  ...          0.2364                  0.07678          NaN

[5 rows x 33 columns]

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [8]:
## id and unnamed, first and last columns are not needed so we will drop those columns

df.drop(columns=['id','Unnamed: 32'],inplace=True)

In [10]:
df.shape

(569, 31)

In [11]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

# train_test split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [13]:
X_train

radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
68         9.029         17.33  ...          0.4228                  0.11750
563       20.920         25.09  ...          0.2929                  0.09873
302       20.090         23.86  ...          0.3294                  0.09469
127       19.000         18.91  ...          0.2841                  0.06541
3         11.420         20.38  ...          0.6638                  0.17300
..           ...           ...  ...             ...                      ...
93        13.450         18.30  ...          0.2678                  0.06603
494       13.160         20.54  ...          0.2687                  0.07429
332       11.220         19.86  ...          0.3292                  0.06522
4         20.290         14.34  ...          0.2364                  0.07678
489       16.690         20.20  ...          0.4677                  0.07623

[455 rows x 30 columns]

In [15]:
y_train

68     B
563    M
302    M
127    M
3      M
      ..
93     B
494    B
332    B
4      M
489    M
Name: diagnosis, Length: 455, dtype: object

In [16]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
X_train.shape

(455, 30)

In [19]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [20]:
y_train

array([0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,

## Converting numpy arrays to pytorch tensors

In [21]:
X_train_tensor = t.from_numpy(X_train)
X_test_tensor = t.from_numpy(X_test)
y_train_tensor = t.from_numpy(y_train)
y_test_tensor = t.from_numpy(y_test)


In [37]:
X_train_tensor.dtype

torch.float64

In [28]:
m = t.rand(30, 1)

In [29]:
m


tensor([[0.2141],
        [0.8561],
        [0.8786],
        [0.6517],
        [0.9437],
        [0.6175],
        [0.8538],
        [0.2520],
        [0.8875],
        [0.4255],
        [0.7126],
        [0.4655],
        [0.0530],
        [0.9510],
        [0.5129],
        [0.3207],
        [0.0351],
        [0.5042],
        [0.4402],
        [0.4072],
        [0.6525],
        [0.3008],
        [0.8098],
        [0.2950],
        [0.1676],
        [0.7597],
        [0.1357],
        [0.1098],
        [0.4791],
        [0.5088]])

# Define the model/Neural Network

In [80]:
class cancer_classifier():
  def __init__(self, x):
    self.weights = t.rand(x.shape[1], 1, dtype = t.float64, requires_grad=True) # 30*1 weight matrix
    self.bias = t.rand(1, dtype = t.float64, requires_grad=True) # 1*1 bias matrix

  def forward(self, x):
    z = t.matmul(x, self.weights) + self.bias
    y_pred = t.sigmoid(z)
    return y_pred

 ## binary cross entropy loss for binary classification
  def loss_function(self, y_pred, y):
    epsilon = 1e-7
    y_pred = t.clamp(y_pred, epsilon, 1-epsilon)
    loss = -(y_train_tensor * t.log(y_pred) + (1-y_train_tensor) * t.log(1-y_pred)).mean()
    return loss



## defining params

In [117]:
l_r = 0.01
epochs = 250

# training pipeline

In [118]:
model = cancer_classifier(X_train_tensor)

In [119]:
model.weights

tensor([[0.7836],
        [0.2556],
        [0.7541],
        [0.9199],
        [0.5934],
        [0.6692],
        [0.1927],
        [0.1552],
        [0.0728],
        [0.5692],
        [0.5126],
        [0.3304],
        [0.0534],
        [0.4757],
        [0.0074],
        [0.6543],
        [0.4958],
        [0.1856],
        [0.7846],
        [0.7227],
        [0.2091],
        [0.4975],
        [0.3878],
        [0.6653],
        [0.8338],
        [0.7214],
        [0.1056],
        [0.9473],
        [0.2924],
        [0.9012]], dtype=torch.float64, requires_grad=True)

In [120]:
model.bias

tensor([0.2147], dtype=torch.float64, requires_grad=True)

# forward pass
# y_pred = w*x + b

In [121]:
for epoch in range(epochs):
  y_pred = model.forward(X_train_tensor)
  loss = model.loss_function(y_pred, y_train_tensor)


  loss.backward()

  # parameter updation

  with t.no_grad():
    model.weights -=  l_r * model.weights.grad
    model.bias -=  l_r * model.bias.grad

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  print(f'epoch: {epoch+1}, loss: {loss.item()}')


epoch: 1, loss: 3.697918263049763
epoch: 2, loss: 3.6840365126553527
epoch: 3, loss: 3.670160949893391
epoch: 4, loss: 3.656075557566091
epoch: 5, loss: 3.6419976280938453
epoch: 6, loss: 3.6279272784302092
epoch: 7, loss: 3.6138646278829336
epoch: 8, loss: 3.5998097982191286
epoch: 9, loss: 3.5857629136650453
epoch: 10, loss: 3.5717241010004797
epoch: 11, loss: 3.5576934895659655
epoch: 12, loss: 3.5436712113455995
epoch: 13, loss: 3.529657400999842
epoch: 14, loss: 3.5156521959244733
epoch: 15, loss: 3.5016557362990572
epoch: 16, loss: 3.487668165137009
epoch: 17, loss: 3.4736896283368903
epoch: 18, loss: 3.459701603109818
epoch: 19, loss: 3.445453067967618
epoch: 20, loss: 3.4310651000826793
epoch: 21, loss: 3.4166871115947393
epoch: 22, loss: 3.4023192713215007
epoch: 23, loss: 3.3879511783793994
epoch: 24, loss: 3.373365678470934
epoch: 25, loss: 3.3587910761422703
epoch: 26, loss: 3.3442275595778246
epoch: 27, loss: 3.329675320717967
epoch: 28, loss: 3.315134555298198
epoch: 29, 

In [122]:
model.weights

tensor([[ 0.3390],
        [-0.0397],
        [ 0.2858],
        [ 0.4808],
        [ 0.1263],
        [ 0.0318],
        [-0.4249],
        [-0.4520],
        [-0.3132],
        [ 0.2178],
        [ 0.0988],
        [ 0.2104],
        [-0.3611],
        [ 0.1059],
        [-0.1541],
        [ 0.1619],
        [ 0.0566],
        [-0.2947],
        [ 0.6278],
        [ 0.2801],
        [-0.2817],
        [ 0.1695],
        [-0.1221],
        [ 0.1929],
        [ 0.3510],
        [ 0.1220],
        [-0.4954],
        [ 0.3183],
        [-0.0805],
        [ 0.3688]], dtype=torch.float64, requires_grad=True)

In [123]:
model.bias

tensor([0.0263], dtype=torch.float64, requires_grad=True)

In [132]:
# model eval
with t.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred_class = (y_pred > 0.9).float()


In [133]:
y_pred_class

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
      

In [134]:
acc = (y_pred_class == y_test_tensor).float().mean()

In [135]:
acc

tensor(0.6551)