<a href="https://colab.research.google.com/github/ishwerdutt/pytorch/blob/main/Tensors_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
print(torch.__version__)

2.5.1+cu124


In [5]:
if torch.cuda.is_available():
  print("Gpu is available")
  print(torch.cuda.get_device_name(0))
else:
  print("gpu not available")

Gpu is available
Tesla T4


In [7]:
## Creating empty
torch.empty(2,3)

tensor([[1.4229e-33, 0.0000e+00, 1.4844e-33],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [8]:
## using zeros, all values are zeros
torch.zeros(2, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
## using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
#using rand,
torch.rand(2,3)

tensor([[0.9954, 0.4615, 0.6808],
        [0.5821, 0.3865, 0.0219]])

if we want to produce same values again, then we have to set manual_seed()

In [11]:
# using rand, and manual seed
torch.manual_seed(50)
torch.rand(2,4)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877]])

In [12]:
torch.manual_seed(50)
torch.rand(2,4)

tensor([[0.6180, 0.0687, 0.3893, 0.0404],
        [0.4013, 0.1442, 0.4605, 0.4877]])

**creating custom tensor**

In [13]:
## using torch.tensor

torch.tensor([[1, 2, 3],
             [4, 5, 6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

## other ways


In [22]:
# arange
print("using arange")
torch.arange(0, 5)
a = torch.arange(0, 5, 2)  ## 2 is putting the difference of two between each of the element
print(a)
print("using linespace")
b = torch.linspace(0, 20, 10) #range(0, 20) and 10 is the number of elements
print(b)
print("using eye") ## identity matrix of size 5*5
c = torch.eye(5)
print(c)
print("using full")
d = torch.full((3, 3), 5) # 3*3 matrix and every element of the matrix is 5
print(d)

using arange
tensor([0, 2, 4])
using linespace
tensor([ 0.0000,  2.2222,  4.4444,  6.6667,  8.8889, 11.1111, 13.3333, 15.5556,
        17.7778, 20.0000])
using eye
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full
tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## tensor shapes


In [25]:
x = torch.rand(5,3)
x.shape

torch.Size([5, 3])

creating an empty tensor of shaoe like x

In [26]:
torch.empty_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [28]:
# using zero_like
torch.zeros_like(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [29]:
torch.ones_like(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

torch.rand_like(), this will not work, we have to explicitly specify datatype for this

datatypes

In [32]:
torch.ones((5,6), dtype=torch.int32)

tensor([[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]], dtype=torch.int32)

# Mathematical operations

In [33]:
x = torch.rand(5,8)

In [34]:
print(x + 2)
print(x-2)
print(x*100//2)

tensor([[2.9486, 2.4388, 2.4589, 2.0359, 2.3525, 2.0389, 2.3880, 2.1319],
        [2.5018, 2.8077, 2.9322, 2.5680, 2.5034, 2.2074, 2.4779, 2.4203],
        [2.4014, 2.0436, 2.6490, 2.9007, 2.8274, 2.3785, 2.7518, 2.2839],
        [2.7220, 2.8421, 2.2474, 2.6834, 2.0551, 2.7824, 2.7901, 2.9596],
        [2.6065, 2.5926, 2.7300, 2.9768, 2.9680, 2.1494, 2.9826, 2.7921]])
tensor([[-1.0514, -1.5612, -1.5411, -1.9641, -1.6475, -1.9611, -1.6120, -1.8681],
        [-1.4982, -1.1923, -1.0678, -1.4320, -1.4966, -1.7926, -1.5221, -1.5797],
        [-1.5986, -1.9564, -1.3510, -1.0993, -1.1726, -1.6215, -1.2482, -1.7161],
        [-1.2780, -1.1579, -1.7526, -1.3166, -1.9449, -1.2176, -1.2099, -1.0404],
        [-1.3935, -1.4074, -1.2700, -1.0232, -1.0320, -1.8506, -1.0174, -1.2079]])
tensor([[47., 21., 22.,  1., 17.,  1., 19.,  6.],
        [25., 40., 46., 28., 25., 10., 23., 21.],
        [20.,  2., 32., 45., 41., 18., 37., 14.],
        [36., 42., 12., 34.,  2., 39., 39., 47.],
        [30., 29.,

In [35]:
x = torch.rand(5,8)
y = torch.rand(5,8)

In [36]:
x+y

tensor([[1.0821, 1.0620, 0.5898, 0.9048, 0.2467, 0.7683, 1.4784, 1.2559],
        [0.9737, 1.7379, 0.8583, 0.8708, 0.5930, 0.6672, 0.7085, 1.0095],
        [1.5476, 1.5348, 1.3849, 0.6942, 0.8732, 1.8441, 1.3605, 1.0464],
        [1.3485, 1.7280, 0.5918, 1.1336, 1.2087, 1.5116, 0.6710, 0.3592],
        [1.6476, 0.7095, 1.1784, 0.5664, 0.7163, 0.7950, 1.4537, 1.6239]])

In [37]:
x-y

tensor([[ 0.0862,  0.8636,  0.0487,  0.2452,  0.0609, -0.2603,  0.4621, -0.2520],
        [-0.3700,  0.0286, -0.4741,  0.6665, -0.0882,  0.0664, -0.6118,  0.5564],
        [-0.1412, -0.0818, -0.2261, -0.4117,  0.7477,  0.0126,  0.5283,  0.2612],
        [-0.2796, -0.1230,  0.5050,  0.0140, -0.3636, -0.0103,  0.6573,  0.2667],
        [ 0.2313, -0.0778,  0.7189, -0.0340, -0.4088,  0.1066,  0.0666,  0.0281]])

In [38]:
x//y

tensor([[ 1.,  9.,  1.,  1.,  1.,  0.,  1.,  0.],
        [ 0.,  1.,  0.,  7.,  0.,  1.,  0.,  3.],
        [ 0.,  0.,  0.,  0., 12.,  1.,  2.,  1.],
        [ 0.,  0., 12.,  1.,  0.,  0., 97.,  6.],
        [ 1.,  0.,  4.,  0.,  0.,  1.,  1.,  1.]])

In [39]:
torch.abs(x)

tensor([[0.5842, 0.9628, 0.3192, 0.5750, 0.1538, 0.2540, 0.9703, 0.5020],
        [0.3018, 0.8832, 0.1921, 0.7686, 0.2524, 0.3668, 0.0484, 0.7829],
        [0.7032, 0.7265, 0.5794, 0.1412, 0.8105, 0.9284, 0.9444, 0.6538],
        [0.5344, 0.8025, 0.5484, 0.5738, 0.4225, 0.7506, 0.6641, 0.3130],
        [0.9395, 0.3158, 0.9486, 0.2662, 0.1538, 0.4508, 0.7602, 0.8260]])

# tensor operations on GPU

In [40]:
m = torch.rand((50, 200), device = torch.device('cuda'))

In [41]:
m

tensor([[0.3146, 0.1458, 0.3482,  ..., 0.8255, 0.1882, 0.0681],
        [0.7014, 0.0923, 0.6011,  ..., 0.5619, 0.0146, 0.8394],
        [0.8385, 0.7006, 0.1814,  ..., 0.5887, 0.8035, 0.3572],
        ...,
        [0.4103, 0.1352, 0.1398,  ..., 0.6222, 0.7371, 0.6186],
        [0.3882, 0.8989, 0.4404,  ..., 0.9547, 0.2847, 0.7024],
        [0.8698, 0.7927, 0.9569,  ..., 0.8844, 0.8142, 0.9411]],
       device='cuda:0')

moving an existing tensor to gpu

In [45]:
a = torch.ones_like(m)
a.to(torch.device('cuda'))

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], device='cuda:0')

# reshaping

In [46]:
a

tensor([[1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        ...,
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.],
        [1., 1., 1.,  ..., 1., 1., 1.]], device='cuda:0')

In [50]:
a.reshape(10, 10, 10, 10)

tensor([[[[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.]],

         ...,

         [[1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          [1., 1., 1.,  ..., 1., 1., 1.],
          ...,
          [1., 1., 1.,  ..., 1., 1., 

In [51]:
a.flatten()

tensor([1., 1., 1.,  ..., 1., 1., 1.], device='cuda:0')

In [52]:
b =torch.rand(2,3,1)

In [53]:
b

tensor([[[0.0215],
         [0.1281],
         [0.2894]],

        [[0.7914],
         [0.2858],
         [0.6467]]])

In [57]:
b.permute(1, 2, 0)

tensor([[[0.0215, 0.7914]],

        [[0.1281, 0.2858]],

        [[0.2894, 0.6467]]])

Converting torch tensors to numpy array

In [58]:
c = b.numpy()

In [59]:
c

array([[[0.02153909],
        [0.1281079 ],
        [0.28941947]],

       [[0.79144984],
        [0.2857517 ],
        [0.6467202 ]]], dtype=float32)